# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questionCheckUI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_questionCheck(object):
    def setupUi(self, questionCheck):
        questionCheck.setObjectName("questionCheck")
        questionCheck.resize(521, 265)
        self.horizontalLayout = QtWidgets.QHBoxLayout(questionCheck)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(questionCheck)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.A_necessity = QtWidgets.QCheckBox(self.groupBox)
        self.A_necessity.setObjectName("A_necessity")
        self.verticalLayout.addWidget(self.A_necessity)
        self.A_suggestion = QtWidgets.QCheckBox(self.groupBox)
        self.A_suggestion.setObjectName("A_suggestion")
        self.verticalLayout.addWidget(self.A_suggestion)
        self.B_necessity = QtWidgets.QCheckBox(self.groupBox)
        self.B_necessity.setObjectName("B_necessity")
        self.verticalLayout.addWidget(self.B_necessity)
        self.B_suggestion = QtWidgets.QCheckBox(self.groupBox)
        self.B_suggestion.setObjectName("B_suggestion")
        self.verticalLayout.addWidget(self.B_suggestion)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(questionCheck)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.allRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.allRadioButton.setChecked(True)
        self.allRadioButton.setObjectName("allRadioButton")
        self.verticalLayout_3.addWidget(self.allRadioButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.partRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.partRadioButton.setObjectName("partRadioButton")
        self.horizontalLayout_3.addWidget(self.partRadioButton)
        self.lowSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.lowSpinBox.setEnabled(False)
        self.lowSpinBox.setMinimum(1)
        self.lowSpinBox.setMaximum(13)
        self.lowSpinBox.setObjectName("lowSpinBox")
        self.horizontalLayout_3.addWidget(self.lowSpinBox)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.upperSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.upperSpinBox.setEnabled(False)
        self.upperSpinBox.setMinimum(1)
        self.upperSpinBox.setMaximum(13)
        self.upperSpinBox.setProperty("value", 13)
        self.upperSpinBox.setObjectName("upperSpinBox")
        self.horizontalLayout_3.addWidget(self.upperSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(questionCheck)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(questionCheck)
        self.buttonBox.accepted.connect(questionCheck.accept)
        self.buttonBox.rejected.connect(questionCheck.reject)
        QtCore.QMetaObject.connectSlotsByName(questionCheck)

    def retranslateUi(self, questionCheck):
        _translate = QtCore.QCoreApplication.translate
        questionCheck.setWindowTitle(_translate("questionCheck", "审核问卷数据"))
        self.groupBox.setTitle(_translate("questionCheck", "审核内容"))
        self.A_necessity.setText(_translate("questionCheck", "问卷A审核-必要性"))
        self.A_suggestion.setText(_translate("questionCheck", "问卷A审核-提示性"))
        self.B_necessity.setText(_translate("questionCheck", "问卷B审核-必要性"))
        self.B_suggestion.setText(_translate("questionCheck", "问卷B审核-提示性"))
        self.groupBox_2.setTitle(_translate("questionCheck", "调查小区范围"))
        self.allRadioButton.setText(_translate("questionCheck", "全部"))
        self.partRadioButton.setText(_translate("questionCheck", "选择"))
        self.label.setText(_translate("questionCheck", "至"))

